development:
  adapter: postgresql
  encoding: utf8
  database: sop_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sop_test
  pool: 5
  username: 
  password: